# Generated by Django 5.1.1 on 2024-10-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('elec', 'Electronics'), ('ktc', 'Kitchen Appliances'), ('clt', 'Clothing'), ('fur', 'Furniture')], max_length=32),
        ),
    ]
