# Generated by Django 5.1.1 on 2024-11-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_watchlist_user_bid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
